# game constants


#screen display
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720


#Asteroid config
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS


#Player config
PLAYER_RADIUS = 20 # size of player ship
PLAYER_TURN_SPEED = 300
